spring:
  application:
    name: eureka-server
#Tomcat Embedded Server Configuration
server:
  port: 8761
#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"